name: example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  dio: ^5.7.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.4
  sentry: ^8.9.0
  catcher:
    path: ../

dev_dependencies:
  very_good_analysis: ^6.0.0

  flutter_test:
    sdk: flutter
flutter:


  uses-material-design: true
